name: sophie
description: "sophie , app para ayudar a desarrollar habilidades en personas nuevas a la programacion"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  dio: ^5.5.0
  syncfusion_flutter_datagrid: ^26.1.41
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  toastification: ^2.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/estrellaM.png
